#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Symbt3NativeAccumulatorAuthorityCounters {
    pub full_accumulator_workload: bool,
    pub smoke_profile: bool,
    pub workload_kind: Symbt3NativeAccumulatorAuthorityWorkload,
    pub main_whir_num_vars: usize,
    pub main_oracle_len: usize,
    pub top_level_whir_proof_count: usize,
    pub family_columnar_subproof_count: usize,
    pub backend_table_count: usize,
    pub native_multi_oracle: bool,
    pub tuple_leaf_layout: String,
    pub whir_instance_count: usize,
    pub root_count: usize,
    pub query_schedule_count: usize,
    pub transcript_count: usize,
    pub native_oracle_pcs_opening_count: usize,
    pub logical_oracle_count: usize,
    pub native_manifest_source_oracle_count: usize,
    pub native_message_oracle_count: usize,
    pub accumulator_transition_claims: usize,
    pub source_r1cs_residual_verifier_evaluations: usize,
    pub rlc_batching_bits: usize,
    pub rlc_repetition_count: usize,
    pub rlc_batching_bits_per_repetition: usize,
    pub total_rlc_batching_bits: usize,
    pub effective_soundness_bits: usize,
    pub native_oracle_eval_claim_count: usize,
    pub fallback_used: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Symbt3NativeAccumulatorAuthorityProfileMetadata {
    pub workload_kind: Symbt3NativeAccumulatorAuthorityWorkload,
    pub full_accumulator_workload: bool,
    pub smoke_profile: bool,
    pub native_profile: Option<Symbt3NativeOracleProfile>,
    pub manifest_policy: Option<ManifestCommitmentPolicy>,
    pub source_policy: Option<SourceCommitmentPolicy>,
    pub message_oracle_policy: Option<Symbt3MessageOraclePolicy>,
    pub root_policy: NativeOracleRootPolicy,
    pub zk_status: Symbt3ZkStatus,
    pub multi_oracle_mode: Symbt3NativeMultiOracleMode,
    pub tuple_leaf_layout: String,
    pub rlc_batching_bits: Option<usize>,
    pub rlc_repetition_count: usize,
    pub rlc_batching_bits_per_repetition: usize,
    pub total_rlc_batching_bits: usize,
    pub effective_soundness_bits: usize,
    pub target_soundness_bits: usize,
    pub soundness_bound_bits: usize,
    pub committed_private_component_count: usize,
    pub native_manifest_source_oracle_count: usize,
    pub native_message_round_count: usize,
    pub native_message_oracle_count: usize,
    pub logical_oracle_count: usize,
    pub whir_instance_count: usize,
    pub root_count: usize,
    pub query_schedule_count: usize,
    pub transcript_count: usize,
    pub native_oracle_pcs_opening_count: usize,
    pub batch_size: usize,
    pub batch_axis_log_size: usize,
    pub message_round_layouts: Vec<Symbt3NativeRoundMessageOracleLayoutV1>,
    pub top_level_whir_proof_count: usize,
    pub family_columnar_subproof_count: usize,
    pub message_to_trace_binding_count: usize,
    pub semantic_profile_version: u32,
    pub required_semantic_families: Symbt3FoldingIntegritySemanticFamilies,
    pub k5_masking_available: bool,
    pub monolithic_fallback: bool,
    pub product_default_route_attempted: bool,
    pub product_eligible: bool,
    pub native_product_route_version_exists: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Symbt3NativeAccumulatorAuthorityProfileReport {
    pub ok: bool,
    pub full_ok: bool,
    pub workload_kind_ok: bool,
    pub full_accumulator_workload: bool,
    pub smoke_profile: bool,
    pub native_profile_ok: bool,
    pub native_manifest_policy_ok: bool,
    pub native_source_policy_ok: bool,
    pub native_message_policy_ok: bool,
    pub canonical_root_policy_ok: bool,
    pub non_zk_status_ok: bool,
    pub tuple_leaf_mode_ok: bool,
    pub tuple_leaf_shape_ok: bool,
    pub rlc_soundness_ok: bool,
    pub committed_private_policy_ok: bool,
    pub message_oracle_count_ok: bool,
    pub required_families_ok: bool,
    pub semantic_profile_version_ok: bool,
    pub no_monolithic_fallback: bool,
    pub product_routing_unchanged: bool,
    pub family_columnar_subproof_count: usize,
    pub native_multi_oracle: bool,
    pub tuple_leaf_layout: String,
    pub logical_oracle_count: usize,
    pub native_message_round_count: usize,
    pub native_message_oracle_count: usize,
    pub native_oracle_pcs_opening_count: usize,
    pub rlc_batching_bits: Option<usize>,
    pub rlc_repetition_count: usize,
    pub rlc_batching_bits_per_repetition: usize,
    pub total_rlc_batching_bits: usize,
    pub effective_soundness_bits: usize,
    pub gate_ok: bool,
}

#[derive(Debug, Clone)]
pub struct Symbt3NativeAccumulatorAuthorityProof {
    pub version: u64,
    pub proof_kind: Symbt3NativeFoldingProofKind,
    pub workload_kind: Symbt3NativeAccumulatorAuthorityWorkload,
    pub profile_digest: Digest32,
    pub accumulator_instance_digest: Digest32,
    pub public_statement_digest: Digest32,
    pub whir_param_digest: Digest32,
    pub native_binding_digest: Digest32,
    pub main_symbt3_relation_id: Digest32,
    pub main_symbt3_proof_digest: Digest32,
    pub rlc_tuple_leaf_root: Digest32,
    pub rlc_tuple_leaf_layout_digest: Digest32,
    pub native_oracle_descriptor_digest: Digest32,
    pub native_message_roots_digest: Digest32,
    pub native_message_roots: Vec<Digest32>,
    pub manifest_oracle_root: Digest32,
    pub source_oracle_root: Digest32,
    pub batch_manifest_root: Digest32,
    pub old_accumulator_digest: Digest32,
    pub new_accumulator_digest: Digest32,
    pub round_challenges: Vec<BabyBear>,
    pub main_symbt3_whir_proof: WhirProof,
    pub rlc_tuple_leaf_multi_oracle_proof: Symbt3TupleLeafMultiOracleProof,
    pub counters: Symbt3NativeAccumulatorAuthorityCounters,
}

